### ISSUE TITLE
Update in-place even there is no change on template

### ISSUE THREAD

**Issue by overmike** [taiidani/terraform-provider-jenkins#19]
Great provider and thanks for the effort.

It seems like the template field will be replaced by the remote jenkins project config.xml which cause `terraform apply` try to update the jenkins project again even with no change.

I suggest to store the remote jenkins project config.xml in a separate terraform attribute reference. whenever the provider refresh state, it should render the template and compare to config.xml. 

Not much experience on terraform provider internal, just a suggestion from observation

**Comment by taiidani** [comment]
Hi @overmike -- you bring up a good point! The config.xml is a tricky one to validate against since, as you've spotted, Jenkins has the tendency to modify it after creation causing drift.

One especially difficult behavior to call out is that the XML includes items not part of the original job. The easiest example of this is how a "folder" job's XML will contain entries for the jobs underneath that folder. Creating any job within a folder will cause the folder resource's template to drift. Simply comparing a rendered config.xml file against the remote file would always lead to destructive outcomes in these situations.

My provider currently sidesteps the problem by encouraging the use of the "ignore_changes" lifecycle property, but I'm open to more built-in solutions! I have thought about parsing the raw XML and comparing only individual elements of it so the rest of the file can drift as needed. Doing that would be a backwards incompatible change, but may be worth it.

**Comment by taiidani** [comment]
@overmike After some experimentation I'm thinking the backwards-incompatible change is worth it. I'm updating the `jenkins_folder` resource to be XML aware in #24. This will require end-users refactor their own `.tf` files to match though.

For generic Jobs I'll have to create entirely new types (e.g. `jenkins_job_freestyle`, `jenkins_job_pipeline`) which might not get into the 0.7 release, but as they won't be breaking changes they can be fast-follow or community PRs.

**Comment by overmike** [comment]
Thanks will try the new release
