### ISSUE TITLE
Error: Computed attributes cannot be set

### ISSUE THREAD

**Issue by ealbarqat** [taiidani/terraform-provider-jenkins#50]
Hello , 
we are using jenkins provider  and it got the latest update which seems not back-ported 

we didn't change any configuration on jenkins templates and we faced this issue which was solved by returning to version 6:

Error: Computed attributes cannot be set
 in resource "jenkins_folder" "terraform-folder":
  64:   template    = <<EOT
  65: <com.cloudbees.hudson.plugins.folder.Folder plugin="cloudbees-folder@6.6">
  66:     <actions/>
  67:     <description>{{ .Description }}</description>
  68:     <properties>
  69:     <com.cloudbees.hudson.plugins.folder.properties.AuthorizationMatrixProperty>
2021-05-31T14:06:55.595Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
  70:         <inheritanceStrategy class="org.jenkinsci.plugins.matrixauth.inheritance.InheritParentStrategy"/>
  71:         {{ range $value := .Permissions }}
  72:         <permission>{{ $value }}</permission>
  73:         {{ end }}
  74:     </com.cloudbees.hudson.plugins.folder.properties.AuthorizationMatrixProperty>
  75:     </properties>
  76:     <icon class="com.cloudbees.hudson.plugins.folder.icons.StockFolderIcon"/>
  77: </com.cloudbees.hudson.plugins.folder.Folder>
  78: EOT
  
  Computed attributes cannot be set, but a value was set for "template".

**Comment by taiidani** [comment]
Hi @ealbarqat -- this was an intentional backwards-incompatible change around the `jenkins_folder` resource. See the [0.7 release notes](https://github.com/taiidani/terraform-provider-jenkins/releases/tag/v0.7.0) for details. The tl;dr of it is that `jenkins_job` is now the only resource supporting custom XML and should be able to satisfy your use case, while `jenkins_folder` has been realigned to be less dynamic in order to support explicit properties.

Apologies for the disruption!
